upstream web {
    zone web 64k;
    server tmr-web.internal:3000 resolve;
}

upstream api {
    zone api 64k;
    server tmr-api.internal:4000 resolve;
}

upstream invoice_api {
    zone invoice_api 64k;
    server tmr-invoice-api.internal:5000 resolve;
}

resolver [fdaa::3]:53;

server {
    listen 80;
    server_name _;
    client_max_body_size 10m;

    location /invoice-generator/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /invoice-generator/index.html;
    }

    location / {
        proxy_pass http://web;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
        proxy_pass http://api;
    }

    location /uploads/ {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://api/uploads/;
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "public, max-age=86400";
    }

    location = /uploads {
        return 301 /uploads/;
    }

    location /temp-assets/ {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://api/temp-assets/;
    }

    location /invoice/ {
        proxy_pass http://invoice_api;
        proxy_set_header Host $host;
    }

}
