upstream web {
    zone web 64k;
    server tmr-web.fly.dev:443;
}

upstream api {
    zone api 64k;
    server tmr-api.fly.dev:443;
}

upstream tmr_api {
    server tmr-api:4000;
}

upstream invoice_api {
    zone invoice_api 64k;
    server tmr-invoice-api.fly.dev:443;
}

resolver [fdaa::3]:53;

server {
    listen 80;
    server_name _;
    client_max_body_size 10m;

    location /invoice-generator/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /invoice-generator/index.html;
    }

    location ^~ /uploads/ {
        proxy_pass http://tmr_api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass https://web;
        proxy_ssl_server_name on;
        proxy_ssl_name tmr-web.fly.dev;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
        proxy_pass https://api;
        proxy_ssl_server_name on;
        proxy_ssl_name tmr-api.fly.dev;
    }

    location = /uploads {
        return 301 /uploads/;
    }

    location /temp-assets/ {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://api/temp-assets/;
    }

    location /invoice/ {
        proxy_pass https://invoice_api;
        proxy_ssl_server_name on;
        proxy_ssl_name tmr-invoice-api.fly.dev;
        proxy_set_header Host $host;
    }

}
