server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = / {
    return 302 https://$host/invoice-generator/;
  }

  location / {
    try_files $uri $uri/ /invoice-generator/index.html;
  }
}
